USE [master]
GO
/****** Object:  Database [DBQuanLyNhaTro]    Script Date: 18/05/2023 11:56:47 CH ******/
CREATE DATABASE [DBQuanLyNhaTro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBQuanLyNhaTro', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DBQuanLyNhaTro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBQuanLyNhaTro_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DBQuanLyNhaTro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DBQuanLyNhaTro] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBQuanLyNhaTro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DBQuanLyNhaTro] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET ARITHABORT OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET  MULTI_USER 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DBQuanLyNhaTro] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DBQuanLyNhaTro] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DBQuanLyNhaTro] SET QUERY_STORE = OFF
GO
USE [DBQuanLyNhaTro]
GO
/****** Object:  Table [dbo].[DANHGIA]    Script Date: 18/05/2023 11:56:47 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DANHGIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MaND] [int] NOT NULL,
	[MaNT] [int] NOT NULL,
	[Like_Dislike] [bit] NOT NULL,
	[NoiDung] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_DANHGIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAINHA]    Script Date: 18/05/2023 11:56:47 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAINHA](
	[MaLoaiNha] [int] NOT NULL,
	[TenLoaiNha] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_LOAINHA] PRIMARY KEY CLUSTERED 
(
	[MaLoaiNha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NGUOIDUNG]    Script Date: 18/05/2023 11:56:47 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NGUOIDUNG](
	[MaND] [int] NOT NULL,
	[TenND] [nvarchar](100) NOT NULL,
	[GioiTinh] [bit] NOT NULL,
	[SoDienThoai] [varchar](12) NOT NULL,
	[SoNha] [nvarchar](50) NULL,
	[Duong] [nvarchar](50) NULL,
	[Phuong] [nvarchar](50) NULL,
	[Quan] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
 CONSTRAINT [PK_NGUOIDUNG] PRIMARY KEY CLUSTERED 
(
	[MaND] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHATRO]    Script Date: 18/05/2023 11:56:47 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHATRO](
	[MaNT] [int] NOT NULL,
	[MaLoaiNha] [int] NOT NULL,
	[MaND] [int] NOT NULL,
	[DienTich] [float] NOT NULL,
	[GiaPhong] [float] NOT NULL,
	[SoNha] [nvarchar](50) NOT NULL,
	[Duong] [nvarchar](50) NOT NULL,
	[Phuong] [nvarchar](50) NOT NULL,
	[Quan] [nvarchar](50) NOT NULL,
	[MoTa] [text] NOT NULL,
	[NgayDang] [date] NOT NULL,
 CONSTRAINT [PK_NHATRO] PRIMARY KEY CLUSTERED 
(
	[MaNT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DANHGIA]  WITH CHECK ADD  CONSTRAINT [FK_DANHGIA_NGUOIDUNG] FOREIGN KEY([MaND])
REFERENCES [dbo].[NGUOIDUNG] ([MaND])
GO
ALTER TABLE [dbo].[DANHGIA] CHECK CONSTRAINT [FK_DANHGIA_NGUOIDUNG]
GO
ALTER TABLE [dbo].[DANHGIA]  WITH CHECK ADD  CONSTRAINT [FK_DANHGIA_NHATRO] FOREIGN KEY([MaNT])
REFERENCES [dbo].[NHATRO] ([MaNT])
GO
ALTER TABLE [dbo].[DANHGIA] CHECK CONSTRAINT [FK_DANHGIA_NHATRO]
GO
ALTER TABLE [dbo].[NHATRO]  WITH CHECK ADD  CONSTRAINT [FK_NHATRO_LOAINHA] FOREIGN KEY([MaLoaiNha])
REFERENCES [dbo].[LOAINHA] ([MaLoaiNha])
GO
ALTER TABLE [dbo].[NHATRO] CHECK CONSTRAINT [FK_NHATRO_LOAINHA]
GO
ALTER TABLE [dbo].[NHATRO]  WITH CHECK ADD  CONSTRAINT [FK_NHATRO_NGUOIDUNG] FOREIGN KEY([MaND])
REFERENCES [dbo].[NGUOIDUNG] ([MaND])
GO
ALTER TABLE [dbo].[NHATRO] CHECK CONSTRAINT [FK_NHATRO_NGUOIDUNG]
GO
ALTER TABLE [dbo].[NGUOIDUNG]  WITH CHECK ADD  CONSTRAINT [CK_NGUOIDUNG] CHECK  (([SoDienThoai]>=(10)))
GO
ALTER TABLE [dbo].[NGUOIDUNG] CHECK CONSTRAINT [CK_NGUOIDUNG]
GO
ALTER TABLE [dbo].[NGUOIDUNG]  WITH CHECK ADD  CONSTRAINT [CK_NGUOIDUNG_1] CHECK  (([Email] like '%_@__%.__%'))
GO
ALTER TABLE [dbo].[NGUOIDUNG] CHECK CONSTRAINT [CK_NGUOIDUNG_1]
GO
ALTER TABLE [dbo].[NHATRO]  WITH CHECK ADD  CONSTRAINT [CK_NHATRO] CHECK  (([GiaPhong]>(0)))
GO
ALTER TABLE [dbo].[NHATRO] CHECK CONSTRAINT [CK_NHATRO]
GO
ALTER TABLE [dbo].[NHATRO]  WITH CHECK ADD  CONSTRAINT [CK_NHATRO_1] CHECK  (([DienTich]>(10)))
GO
ALTER TABLE [dbo].[NHATRO] CHECK CONSTRAINT [CK_NHATRO_1]
GO
USE [master]
GO
ALTER DATABASE [DBQuanLyNhaTro] SET  READ_WRITE 
GO
